# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('detainer_count', models.IntegerField()),
            ],
        ),
    ]
